### ISSUE TITLE
rainbow_beat FastLED problem

### ISSUE THREAD

**Issue by johnwatterson** [marett/rainbow-beats#1]
exit status 1
elements of array 'CBGR leds [150]' have incomplete type

Using SMD 5050 led strips with 150 leds on each strip. Any ideas?
#define LED_DT 5                                             // Serial data pin
#define LED_CK 11                                             // Clock pin for WS2801 or APA102
#define COLOR_ORDER BGR                                      // It's GRB for WS2812B and BGR for APA102
#define LED_TYPE 5050                                      // What kind of strip are you using (APA102, WS2801 or WS2812B)?
#define NUM_LEDS 150

**Comment by marett** [comment]
I think you have the wrong repo, sorry friend.
